### ISSUE TITLE
Create detailed documentation for new developers

### ISSUE THREAD

**Issue by sesa929** [serlo/backlog#17]
![](https://github.trello.services/images/mini-trello-icon.png) [Dokumentation für neue Entwickler](https://trello.com/c/GDAzEpvM/58-dokumentation-f%C3%BCr-neue-entwickler)

## Documentation pages which need to be created

- [x] #62
- [x] #63
- [x] #64
- [x] #65
- [x] #66

=> [Documentation](https://github.com/serlo/documentation/wiki/Introduction-to-the-Serlo-Editor)

**Comment by kulla** [comment]
- [ ] Introduction
  - Links to redux, redux-saga, etc
  - [ ] Link to editr-io presentation
  - [ ] How to setup redux-devtools
- [ ] Glossar (Words like "Serialized", "Document", "Sub-Document")
- [ ] Directory-Structure and description of packages
- [ ] What happens when we have a change in the editor (redux process)?
- [ ] Best Practices to write code / plugins
  - Needs to be discussed
- [ ] Copy & Paste all current documententation in one place

**Comment by sesa929** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dokumentation für neue Entwickler](https://trello.com/c/GDAzEpvM/58-dokumentation-f%C3%BCr-neue-entwickler)

**Comment by anbestCL** [comment]
Code documentation will be done at a later point in time.

- [ ] Text-Selection (needs to be done in https://github.com/edtr-io/edtr-io/pull/398)
- [ ] StateExecuter (`resolve()`, `reject()` and `next()`)
- [ ] Actions
- [ ] Store
- [ ] StateTypes
  - serializedScalar
