### ISSUE TITLE
Plugin selection menu can't be easily closed by clicking outside of the component

### ISSUE THREAD

**Issue by CodingDive** [serlo/backlog#255]
Steps to reproduce
1. Get the plugin suggestion menu to open
2. Try to click outside of it
3. It sometimes jumps visually but it takes a double click or the newly implemented ESC key to really close it

Tested locally, staging and in production, all environments seem to have the same issue.

![plugin_suggestion](https://github.com/serlo/frontend/assets/28842311/54aefaf5-40b0-408a-a003-7a263c6f185c)

**Comment by hejtful** [comment]
This seems to me like another of the focus issues - because no other plugin gets focused, the currently focused plugin doesn't lose focus, therefore the suggestions stay visible.

I opened [a PR with a temporary fix](https://github.com/serlo/frontend/pull/2659), but I'm not sure if we want to merge it or wait for the general focus re-work.
